language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker-compose -f docker-compose-build.yaml build
  - docker tag udagram-api-feed nemboche/udagram-api-feed:latest
  - docker tag udagram-api-user nemboche/udagram-api-user:latest
  - docker tag udagram-reverseproxy nemboche/udagram-reverseproxy:latest
  - docker tag udagram-frontend:local nemboche/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push nemboche/udagram-api-feed:latest
  - docker push nemboche/udagram-api-user:latest
  - docker push nemboche/udagram-reverseproxy:latest
  - docker push nemboche/udagram-frontend:latest